### ISSUE TITLE
Problem with IsGentleAlgebra?

### ISSUE THREAD

**Issue by Nakayamaalgebra** [gap-packages/qpa#24]
Hi,
two small question/observations on QPA (Im not sure whether there is a problem with qpa or I have a thinking error).
1. QPA uses right modules but it seems EndOfModuleOverQuiverAlgebra(M) returns the opposite algebra as what one would expect when using right modules. For example using right modules one should have End_A(A) being isomorphic to A but in QPA End_A(A) is isomorphic to A^{op}.

2. IsGentleAlgebra(NakayamaAlgebra([3,2,2,1],GF(3)));
works fine but
IsGentleAlgebra(NakayamaAlgebra([3,3,2,1],GF(3)));
returns a bug, which is very strange.

**Comment by sunnyquiver** [comment]
Hi, 
For Question 1:  In QPA, if we have maps  f : L -> M and g : M -> N, then the composition is written f * g.  This is described in the manual in the beginning of Chapter 7.  If this is the convention, I hope that we are correct in claiming that End_A(A) is isomorphic to A^{op}?

Best regards, The QPA-team.
