### ISSUE TITLE
ReducedList: name clash with GrpConst

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/qpa#27]
GAP tests which load all packages are broken by the new QPA release:
```
#I  QPA: start reading file 'init.g'
Error, variable `ReducedList' is not bound to an operation at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAPCO\
PTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-stab\
le-snapshot/lib/oper.g:823 called from
```
because `ReducedList` is a function in GrpConst:

```
gap> PageSource(ReducedList);                                     
Showing source in /Users/alexk/gap-4.9.3/pkg/grpconst-2.6.1/gap/upext.gi (from\
 line 231)

#############################################################################
##
#F ReducedList( size, list )
##
ReducedList := function( size, list )
    local rem, types, G, new, i, H, iso, g, h;

    if Length( list ) <= 1 then return list; fi;

    rem   := [1..Length(list)];
...
```

Could you please resolve this quickly?

**Comment by alex-konovalov** [comment]
Ah, and I did not explain what do I mean by "resolve". Because it's already a function in another package (unfortunately, not write protected), I suggest that you use a different name for a newly introduced operation in QPA. Please check that it does not clash with other packages (e.g. y grepping in their code, or by calling `LoadAllPackages();` and checking that it does not go into a break loop.

**Comment by alex-konovalov** [comment]
@sunnyquiver I've noticed that there is no new release yet. If you need more time please let me know and I will disable the latest QPA in favour of its stable version in nightly tests - otherwise I am getting a flood of test failure notifications.

**Comment by sunnyquiver** [comment]
Another version is imminent.

**Comment by alex-konovalov** [comment]
Also, what is the status of https://github.com/oysteins/QPA/ ? I suggest to archive that repository (see https://help.github.com/articles/archiving-a-github-repository/) to make it clear that it's inactive (or delete, or make it private - whatever is appropriate). I've almost submitted an issue there a while ago.

**Comment by sunnyquiver** [comment]
Version 1.29 is now published.

**Comment by alex-konovalov** [comment]
Thanks - picked up! I will close this issue subject to tests passing.

**Comment by alex-konovalov** [comment]
Thanks, this is now resolved.
