### ISSUE TITLE
Excessive output from NthSyzygy

### ISSUE THREAD

**Issue by karinmja** [gap-packages/qpa#29]
I am using the function NthSyzygy extensively in a calculation. It works fine, but generates a lot of output. For instance, one run-through (with n=1) generates:

> Computing syzygy number: 1 ...
> Dimension vector for syzygy: [ 0, 1, 0, 1, 0, 0, 1, 0, 0, 0 ]
> Top of the 1th syzygy: [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ]

Naturally, this becomes rather unreadable in the long run (using ;; after calling the function does not help).
I've commented out the print statements in my local copy of QPA, but I feel the issue should still be adressed.

**Comment by sunnyquiver** [comment]
The print statements from NthSyzygy have been removed and the code has been simplified. 
See commit 0c729f55.  The function now returns the n-th syzygy of the module entered. The function NthSyzygyNC
has been removed.
