### ISSUE TITLE
AllSubmodulesOfModule

### ISSUE THREAD

**Issue by Nakayamaalgebra** [gap-packages/qpa#32]
Hi,
I was experimenting a little with the new program AllSubmodulesOfModule and have a question.
There are 14 Nakayama algebras with a (connected) line as a quiver with 5 points.
But when I use the program AllSubmodulesOfModule to count the number of bimodule submodules of the second radical of the hereditary Nakayama algebra with 5 points (which should correspond to counting the admissible ideals) I just get 10.
But there should be at least 14 such admissible ideals when I have no thinking error.
Thanks for any help.

**Comment by sunnyquiver** [comment]
Thank you very much for reporting this problem/bug.  I hope that we have fixed the bug.
```
gap> A := NakayamaAlgebra(GF(2),[5,4,3,2,1]);
<GF(2)[<quiver with 5 vertices and 4 arrows>]>
gap> M := AlgebraAsModuleOverEnvelopingAlgebra(A);
<[ 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1 ]>
gap> M := RadicalOfModule(M);
<[ 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ]>
gap> M := RadicalOfModule(M);
<[ 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]>
gap> test := AllSubmodulesOfModule(M);;
gap> Length(Flat(test));
14
gap> List(test, Length);
[ 1, 1, 2, 3, 3, 3, 1 ]
```

**Comment by Nakayamaalgebra** [comment]
Thank you very much for the fast fix.
For the Nakayama algebras with a line the numbers should be the Catalan sequence and it seems to be correct now. I do not know many other non-trivial examples very different from this where I know the answer but I will do some tests with other algebras.
