### ISSUE TITLE
Tilting module

### ISSUE THREAD

**Issue by Nakayamaalgebra** [gap-packages/qpa#33]
Hi,
I get the following output:

gap> A:=NakayamaAlgebra([3,2,1],GF(3));P:=IndecProjectiveModules(A)[1];TiltingModule(P,1);
<GF(3)[<quiver with 3 vertices and 2 arrows>]>
<[ 1, 1, 1 ]>
[ 0, [ 0 -> 0:(1,1,1) -> -1:(1,1,1) -> 0, 0 -> 0:(0,1,1) -> -1:(1,1,1) -> 0, 0 -> 0:(0,0,1) -> -1:(1,1,1) -> 0 ] ]

However, the modules P is indecomposable and thus can not be a tilting module over an algebra with 3 simple modules unless I have a thinking error.

**Comment by sunnyquiver** [comment]
Thank you very much for reporting this problem/bug. I hope that we have fixed the bug.

```
gap> A:=NakayamaAlgebra([3,2,1],GF(3));
<GF(3)[<quiver with 3 vertices and 2 arrows>]>
gap> P:=IndecProjectiveModules(A)[1]; 
<[ 1, 1, 1 ]>
gap> TiltingModule(P,1);
false
```

**Comment by Nakayamaalgebra** [comment]
Thank you very much again. A small question: Can the issues section here also be used to ask a question on a qpa input? I try to calculate the endomorphism ring with qpa of a certain module but it takes weeks and does not finish. Maybe someone has an idea for a reason or how to make it quicker? It is not really important but Im very curious.

**Comment by sunnyquiver** [comment]
As I understand the purpose of the issues on Github, is to keep a public record of tasks, enhancements and bugs of QPA.  So I think that issues are not the right forum for such questions.  Maybe the GAP-forum or the Stack Exchange (Mathematics/mathoverflow) with tag "gap" is better suited.  Maybe other parts of the GAP-community can advise us on this.

**Comment by Nakayamaalgebra** [comment]
OK thank you. It is not so important anyway.
