### ISSUE TITLE
Migrating to gap-packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/qpa#4]
We have created new VO at https://github.com/gap-packages and suggest that all GAP packages could eventually migrate there - please consider doing so when it may be appropriate and less disruptive for your package.

**Comment by fingolfin** [comment]
Any comments on on this? We'd be happy to help you with it... Basically, you need to this:

1. Go to the repository settings at https://github.com/gap-system/qpa/settings
2. In the "Danger zone", click on "Transfer ownership"
3. Follow the instructions there (if there are any issues, contact us)
4. Edit any websites or files pointing to https://github.com/gap-system/qpa/ to instead point to https://github.com/gap-packages/qpa/  (though there should also be an automatic redirect)

**Comment by sunnyquiver** [comment]
QPA has now migrated to https://github.com/gap-packages/qpa.

**Comment by fingolfin** [comment]
Thank you! From my point of view, this ticket could be closed -- but perhaps you want to keep it open to remind you of related changes you need to make?
