### ISSUE TITLE
Implement GeneratorsOfPathAlgebra

### ISSUE THREAD

**Issue by nthiery** [gap-packages/qpa#43]
Sometimes one wants to access the generators of the path algebra, without assigning them to special names. In my particular use case, this is for accessing them from Sage. There, a method "GeneratorsOfPathAlgebra" would usefully complement the existing
AssignGeneratorVariables.

Thanks in advance!

**Comment by sunnyquiver** [comment]
There are two methods, that I know, to do this.  Assume that you have defined a path algebra KQ in QPA with vertices and arrows labelled [ v1, v2, v3, a, b, c, d, e ]. 

Method 1: You can access the generators via  KQ.v1,  KQ.v2, KQ.v3, KQ.a, KQ.b, KQ.c, KQ.d and KQ.e.

Method 2: `gens := GeneratorsOfAlgebraWithOne(KQ); ` or `gens := GeneratorsOfAlgebra(KQ);` 
will assign to `gens` the list `[ (1)*v1, (1)*v2, (1)*v3, (1)*a, (1)*b, (1)*c, (1)*d, (1)*e ]` of all the generators of the path algebra, where each individual can be access through  `gens[ 1 ]`, and so on.

**Comment by nthiery** [comment]
Oops, I made a fool of myself by somehow missing the feature, and going down to quick to grep the sources ... with the wrong search ... :-)

Well, let's take this as an occasion to thank you for QPA! And your quick user support!

**Comment by sunnyquiver** [comment]
Thank you very much! 

It is always nice to actually hear that someone is using QPA.
