### ISSUE TITLE
Some problems with QPA-commands

### ISSUE THREAD

**Issue by Nakayamaalgebra** [gap-packages/qpa#44]
Hi,
it seems there are problems with the commands CotiltingModule,IsCotiltingModule and AlmostSplitSequenceInPerpT (and possibly also RightApproximationByPerpT2 ).

Here what I tried and the errors:
gap> A:=NakayamaAlgebra([4,5],GF(3)); 
<GF(3)[<quiver with 2 vertices and 2 arrows>]/<two-sided ideal in <GF(3)[<quiver with 2 vertices and 2 arrows>]>,  
 (1 generators)>> 
gap> RegA:=DirectSumOfQPAModules(IndecProjectiveModules(A)); 
<[ 4, 5 ]> 
gap> sim:=SimpleModules(A); 
[ <[ 1, 0 ]>, <[ 0, 1 ]> ] 
gap> S:=sim[1]; 
<[ 1, 0 ]> 
gap> N:=NthSyzygy(S,2); 
<[ 1, 1 ]> 
gap> U:=AlmostSplitSequenceInPerpT(RegA,N); 
Error, no method found! For debugging hints type ?Recovery from NoMethodFound 
Error, no 2nd choice method found for `IsCotiltingModule' on 1 arguments at /home/bb/Schreibtisch/gap-4.10.2/lib/methsel2.g:25
0 called from 
IsCotiltingModule( T ) at /home/bb/Schreibtisch/gap-4.10.2/pkg/qpa/lib/moduleARtheory.gi:307 called from 
<function "unknown">( <arguments> ) 
called from read-eval loop at *stdin*:38 
type 'quit;' to quit to outer loop 
brk>  
gap> IsCotiltingModule(RegA); 
Error, no method found! For debugging hints type ?Recovery from NoMethodFound 
Error, no 2nd choice method found for `IsCotiltingModule' on 1 arguments at /home/bb/Schreibtisch/gap-4.10.2/lib/methsel2.g:25
0 called from 
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> ) 
called from read-eval loop at *stdin*:38 
type 'quit;' to quit to outer loop 
brk>  
gap> CotiltingModule(RegA,2); 
Error, no method found! For debugging hints type ?Recovery from NoMethodFound 
Error, no 1st choice method found for `ExtOverAlgebra' on 2 arguments at /home/bb/Schreibtisch/gap-4.10.2/lib/methsel2.g:250 c
alled from 
ExtOverAlgebra( N, M ) at /home/bb/Schreibtisch/gap-4.10.2/pkg/qpa/lib/modulehomalg.gi:1573 called from 
<function "unknown">( <arguments> ) 
called from read-eval loop at *stdin*:38 
type 'quit;' to quit to outer loop 
brk>  
gap>

**Comment by sunnyquiver** [comment]
It seems that the way the kernel of a homomorphism is computed has been changed by possible changes in GAP, because I noticed that the kernel just was a vector space, not a module/representation.  I have changed the definition of the kernel to be independent of any general GAP kernel constructions. Then your example computed the way it should, given that you always have to tell QPA that a module _M_ is a cotilting module by applying the command `CotiltingModule(M,2)` (or some other number than 2).  This has to be done before you apply the command `AlmostSplitSequenceInPerpT`. See commit 5a02438 to see the changes.

**Comment by erich-9** [comment]
Great, now it works. Against my expectation, there seems to be no similar problem with cokernels.

Could it be that the reason for this is that the priority of `CoKernelOfAdditiveGeneralMapping` is set to  `SUM_FLAGS+1` but the priority of `KernelOfAdditiveGeneralMapping` was `0`?

**Comment by sunnyquiver** [comment]
Yes, this is probably the explanation.  I didn't think of checking this.  I don't remember why it was done in this way in the first place.
