### ISSUE TITLE
Problem with basis?

### ISSUE THREAD

**Issue by Nakayamaalgebra** [gap-packages/qpa#45]
Hi,
I calculate quiver and relations of the group algebra of the quaternion group over GF(2) with QPA and then get a basis of this quiver algebra.
Note that the quiver algebra has dimension 8 and the basis has 8 elements. But the basis cant generate the algebra as a vector space, since a1a2a1^2 seem to be not generated by this basis elements since the basis elements have length at most three (the last command checks whether a1a2a1^2 is nonzero by checking whether the ideal generated by it is nonzero. By the way, how to obtain the ideal uA of a quiver algebra A for a general element u of A that is in Elements(A) ?)

gap> G:=QuaternionGroup(8);kG:=GroupRing(GF(2),G);A:=AlgebraAsQuiverAlgebra(kG)[1];
<pc group of size 8 with 3 generators>
<algebra-with-one over GF(2), with 3 generators>
<GF(2)[<quiver with 1 vertices and 2 arrows>]/<two-sided ideal in <GF(2)[<quiver with 1 vertices and 2 arrows>]>, (6 generators)>>
gap> Q:=QuiverOfPathAlgebra(A);Display(Q);RelatorsOfFpAlgebra(A);
<quiver with 1 vertices and 2 arrows>
Quiver( ["v1"], [["v1","v1","a1"],["v1","v1","a2"]] )
[ (Z(2)^0)*a1*a2+(Z(2)^0)*a2*a1+(Z(2)^0)*a2^2, (Z(2)^0)*a1^2+(Z(2)^0)*a1*a2+(Z(2)^0)*a2*a1+(Z(2)^0)*a1^3+(Z(2)^0)*a1*a2*a1, (Z(2)^0)*a1^2*a2+(Z(2)^0)*a2*a1^2, (Z(2)^0)*a1^2+(Z(2)^0)*a1*a2+(Z(2)^0)*a2*a1+(Z(2)^0)*a1^3+(Z(2)^0)*a2*a1*a2, (Z(2)^0)*a1^4, 
  (Z(2)^0)*a1^2+(Z(2)^0)*a1*a2+(Z(2)^0)*a2*a1+(Z(2)^0)*a1^2*a2+(Z(2)^0)*a1^3*a2 ]
gap> LoewyLength(A);
5
gap> bas:=BasisVectors(Basis(A));
[ [(Z(2)^0)*v1], [(Z(2)^0)*a1], [(Z(2)^0)*a2], [(Z(2)^0)*a2*a1], [(Z(2)^0)*a1^2], [(Z(2)^0)*a1*a2], [(Z(2)^0)*a1^3], [(Z(2)^0)*a1^2*a2] ]
gap> I_neu:=RightIdeal(A, [A.a1*A.a2*A.a1^2]); M:=RightAlgebraModuleToPathAlgebraMatModule(RightAlgebraModule(A, \*, I_neu));
<right ideal in <GF(2)[<quiver with 1 vertices and 2 arrows>]/<two-sided ideal in <GF(2)[<quiver with 1 vertices and 2 arrows>]>, (6 generators)>>, (1 generators)>
<[ 1 ]>

**Comment by sunnyquiver** [comment]
```
G := QuaternionGroup( 8 );
kG := GroupRing( GF( 2 ), G );
Q := QuiverOfPathAlgebra( A );
Display( Q );
RelatorsOfFpAlgebra( A );
```

Let `u := A.a1 * A.a2 * A.a1^2.` When you enter this into the command line, QPA
computes the normal form of this element, that is, expresses it in terms of the 
chosen basis (the nontips of the ideal of relations with respect to the Groebner
basis). 

```
gap> u := A.a1 * A.a2 * A.a1^2;
[(Z(2)^0)*a1^2+(Z(2)^0)*a1*a2+(Z(2)^0)*a2*a1+(Z(2)^0)*a1^2*a2]   
```
   
So we see that  u  is represented by a sum of paths of length 2 and 3. So modulo
the relations, `a1*a2*a1^2` is equal to `a1*a1 + a1*a2 + a1*a1*a2`.
  
Obtaining the right ideal uA for an arbitrary element in A is what you have done 
already:

```
B := Basis( A );
r := Random( GF( 2 )^8 );
v := LinearCombination( B, r );
test := RightIdeal( A, [ v ] );
```

This is to create a random ideal generated by one elemenet.  If you want to run 
through all these

`allideals := List( Elements( A ), v -> RightIdeal( A, [ v ] ) );`

Does this help?

**Comment by Nakayamaalgebra** [comment]
Thank you very much for your quick answer!
Quiver algebras with non-homogenous ideal can be quite dangerous.
