### ISSUE TITLE
QPA 1.30 tarball contains macOS metadata files, but shouldn't

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/qpa#51]
Apparently the QPA 1.30 release tarball contains `._FOO` files as created by the Apple versions of GNU and BSD tar:
```
._CHANGES
._PackageInfo.g
._README
._version
```
It would be great if the next release avoided adding such files. This should be automatic if one uses the  `release-gap-package` script from [ReleaseTools](https://github.com/gap-system/ReleaseTools).

**Comment by sunnyquiver** [comment]
When I download the package release version of QPA, from [releases](https://github.com/gap-packages/qpa/archive/v1.30.tar.gz) or I clone the repository from [the clone tab](https://github.com/gap-packages/qpa.git), I cannot see any `._FOO` files.  Where am I supposed to find them?

**Comment by fingolfin** [comment]
They are in the tar.gz, but you can only see them if you extract it on Linux or Windows, not on macOS

**Comment by sunnyquiver** [comment]
I get the following on a university linux computer:

```
loginansatt01:~/qpa-1.30$ pwd
/home/ahomey/o/oyvind/qpa-1.30
loginansatt01:~/qpa-1.30$ ls -A
CHANGES		    doc		lib	       read.g	    version
.codecov.yml	    examples	LICENSE        README
CODE_OF_CONDUCT.md  .gitignore	.mailmap       .travis.yml
create-release.sh   init.g	PackageInfo.g  tst
loginansatt01:~/qpa-1.30$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
I still cannot see the `._FOO` files.  Where do I go wrong?

**Comment by erich-9** [comment]
The two tarballs

  - https://files.gap-system.org/gap4/tar.gz/packages/qpa-version-1.30.tar.gz
  - https://github.com/gap-packages/qpa/archive/v1.30.tar.gz

have different contents:

```
Only in qpa-version-1.30: ._CHANGES
Only in qpa-1.30: .codecov.yml
Only in qpa-1.30: CODE_OF_CONDUCT.md
Only in qpa-1.30: create-release.sh
Only in qpa-version-1.30/doc: chap0.html
Only in qpa-version-1.30/doc: chap0_mj.html
Only in qpa-version-1.30/doc: chap0.txt
Only in qpa-version-1.30/doc: chap10.html
Only in qpa-version-1.30/doc: chap10_mj.html
Only in qpa-version-1.30/doc: chap10.txt
Only in qpa-version-1.30/doc: chap11.html
Only in qpa-version-1.30/doc: chap11_mj.html
Only in qpa-version-1.30/doc: chap11.txt
Only in qpa-version-1.30/doc: chap12.html
Only in qpa-version-1.30/doc: chap12_mj.html
Only in qpa-version-1.30/doc: chap12.txt
Only in qpa-version-1.30/doc: chap13.html
Only in qpa-version-1.30/doc: chap13_mj.html
Only in qpa-version-1.30/doc: chap13.txt
Only in qpa-version-1.30/doc: chap1.html
Only in qpa-version-1.30/doc: chap1_mj.html
Only in qpa-version-1.30/doc: chap1.txt
Only in qpa-version-1.30/doc: chap2.html
Only in qpa-version-1.30/doc: chap2_mj.html
Only in qpa-version-1.30/doc: chap2.txt
Only in qpa-version-1.30/doc: chap3.html
Only in qpa-version-1.30/doc: chap3_mj.html
Only in qpa-version-1.30/doc: chap3.txt
Only in qpa-version-1.30/doc: chap4.html
Only in qpa-version-1.30/doc: chap4_mj.html
Only in qpa-version-1.30/doc: chap4.txt
Only in qpa-version-1.30/doc: chap5.html
Only in qpa-version-1.30/doc: chap5_mj.html
Only in qpa-version-1.30/doc: chap5.txt
Only in qpa-version-1.30/doc: chap6.html
Only in qpa-version-1.30/doc: chap6_mj.html
Only in qpa-version-1.30/doc: chap6.txt
Only in qpa-version-1.30/doc: chap7.html
Only in qpa-version-1.30/doc: chap7_mj.html
Only in qpa-version-1.30/doc: chap7.txt
Only in qpa-version-1.30/doc: chap8.html
Only in qpa-version-1.30/doc: chap8_mj.html
Only in qpa-version-1.30/doc: chap8.txt
Only in qpa-version-1.30/doc: chap9.html
Only in qpa-version-1.30/doc: chap9_mj.html
Only in qpa-version-1.30/doc: chap9.txt
Only in qpa-version-1.30/doc: chapBib.html
Only in qpa-version-1.30/doc: chapBib_mj.html
Only in qpa-version-1.30/doc: chapBib.txt
Only in qpa-version-1.30/doc: chapInd.html
Only in qpa-version-1.30/doc: chapInd_mj.html
Only in qpa-version-1.30/doc: chapInd.txt
Only in qpa-version-1.30/doc: chooser.html
Only in qpa-1.30/doc: gap-days-lectures
Only in qpa-version-1.30/doc: lefttoc.css
Only in qpa-version-1.30/doc: manual.css
Only in qpa-version-1.30/doc: manual.js
Only in qpa-version-1.30/doc: manual.pdf
Only in qpa-version-1.30/doc: manual.six
Only in qpa-version-1.30/doc: nocolorprompt.css
Only in qpa-1.30/doc: qpadocumentation.bib
Only in qpa-version-1.30/doc: ._qpadocumentation.xml
Only in qpa-1.30/doc: qpa-exercises.tex
Only in qpa-1.30/doc: qpa-introduction.tex
Only in qpa-version-1.30/doc: ragged.css
Only in qpa-version-1.30/doc: rainbow.js
Only in qpa-version-1.30/doc: times.css
Only in qpa-version-1.30/doc: toggless.css
Only in qpa-version-1.30/doc: toggless.js
Only in qpa-1.30: .gitignore
Only in qpa-1.30: .mailmap
Only in qpa-version-1.30: ._PackageInfo.g
Only in qpa-version-1.30: ._README
Only in qpa-1.30: .travis.yml
Only in qpa-version-1.30: ._version

```

**Comment by sunnyquiver** [comment]
The second tarball is produced on github.com, I guess.  While the second is something I have produced.  So if one would switch to the gitbub-version, all problems are solved?

**Comment by fingolfin** [comment]
No, because the github generated tarball is e.g. missing the HTML version of manual.
You can avoid the "bad" files next time by setting an environment variable before running `tar` on a mac, see https://superuser.com/a/260264/0

However, it is *not* necessary to do this for the 1.30 release; it simply would be nice if future releases did not have this issue.

As suggested above, you could also use https://github.com/gap-system/ReleaseTools for future releases, which automates releases, saves a lot of works this way, catches (and voids) this issue and a bunch more :-). The main drawback for you probably would be that it expects you to also use https://github.com/gap-system/GitHubPagesForGAP ; of course you could just do that, but I fully understand if you'd prefer to keep your existing website setup. But it's trivial to hack `release-gap-package` to not try to update a website driven by GitHubPagesForGAP (just insert `exit 0` before the `notice "Updating website"` line in it). I'd be happy to add a command line flag to it which does the same, too ; only reason it's not there is that so far nobody requested that.

I'll stop annoying you with the advertisement (but should I have peeked your interest, I am available to answer questions or help getting it to work).
