### ISSUE TITLE
Error creating path algebra over a finite field? 

### ISSUE THREAD

**Issue by mikepierce** [gap-packages/qpa#52]
gap> Q := Quiver(2,[[1,2,"a"]]);
    gap> F := Z(17);
    gap> PathAlgebra(F,Q);

This returns an error:

    Error, <F> must be a division ring or field. called from
    <function "PathAlgebra">( <arguments> )
      called from read-eval loop at line 3 of *stdin*

Is it not possible to define path algebras over finite fields with QPA?

**Comment by sunnyquiver** [comment]
The command `Z(17)` is not creating a finite field, just a multiplicative generator of the finite field with 17 elements.  The command `GF(17)` returns the finite field with 17 elements.  So replace `Z(17)` with `GF(17)` and you should be good.
