### ISSUE TITLE
Calculating projective indecomposables for quotient of three-loop quiver won't terminate

### ISSUE THREAD

**Issue by pi-bie** [gap-packages/qpa#53]
I was planning on calculating some examples for the algebra A=k<x,y,z>/(paths of length two), but the following code won't finish (even after 24h):
```
k := Rationals;;
Q := Quiver(1, [ [1, 1, "a"], [1, 1, "b"], [1, 1, "c"] ] );
kQ := PathAlgebra(k,Q);;
AssignGeneratorVariables(kQ);
relations := [a^2, b^2, c^2, a*c, c*a, a*b, b*a, b*c, c*b];
I:=Ideal(kQ, relations);
A := kQ/I;
IndecProjectiveModules(A);
```

Working over a finite field hasn't changed this, nor starting from the one-loop quiver.
To me, it seems that the problem lies in https://github.com/gap-packages/qpa/blob/6486080789192b1bc0a6ca0b633847b6d55e1e66/lib/modulespecial.gi#L53 or thereafter, as a basis for the right ideal in this situation seems to have three-digit length (or so it looks from debugging). Possibly the right ideal doesn't take into account the relations?

**Comment by sunnyquiver** [comment]
I think the problem originates in the construction of the algebra.  If you do the following, namely construct the algebra with the command  `kQ/relations`:

```
gap> k := Rationals;;
gap> Q := Quiver(1, [ [1, 1, "a"], [1, 1, "b"], [1, 1, "c"] ] );
<quiver with 1 vertices and 3 arrows>
gap> kQ := PathAlgebra(k,Q);;
gap> AssignGeneratorVariables(kQ);
#I  Assigned the global variables [ v1, a, b, c ]
gap> relations := [a^2, b^2, c^2, a*c, c*a, a*b, b*a, b*c, c*b];
[ (1)*a^2, (1)*b^2, (1)*c^2, (1)*a*c, (1)*c*a, (1)*a*b, (1)*b*a, (1)*b*c, (1)*c*b ]
gap> A := kQ/relations;
<Rationals[<quiver with 1 vertices and 3 arrows>]/<two-sided ideal in <Rationals[<quiver with 1 vertices and 3 arrows>]>, 
  (9 generators)>>
gap> IndecProjectiveModules(A);
[ <[ 4 ]> ]
```
If you construct the algebra with the command  `kQ/I,` a Groebner basis is not automatically computed as with the command  `kQ/relations`.  The first option is left there so that you can do something with algebras (or ideals of relations) that do not have finite Groebner basis.

**Comment by sunnyquiver** [comment]
I suggest that this issue is closed, as this problem is discussed on page 29 in the manual.  Any objections?

**Comment by pi-bie** [comment]
Sorry for my late reply. Your hint has solved my problem. I had seen the different constructions in the manual, but then forgot about them. Also, contrary to the example in the manual, I got no error running IndecProjectiveModules with the other constructing, thus assuming the construction wasn't the underlying problem.
