### ISSUE TITLE
Problem with IsSymmetricAlgebra?

### ISSUE THREAD

**Issue by Nakayamaalgebra** [gap-packages/qpa#62]
The command IsSymmetricAlgebra says that a group algebra is not symmetric:

G:=DihedralGroup(8);Size(G);
K:=GF(2);R:=GroupRing(K,G);
A:=AlgebraAsQuiverAlgebra(R)[1];
gap> IsSymmetricAlgebra(A);
false

gap> C:=AlgebraAsModuleOverEnvelopingAlgebra(A);D:=DualOfAlgebraAsModuleOverEnvelopingAlgebra(A);IsomorphicModules(C,D);
<[ 8 ]>
<[ 8 ]>
true

**Comment by sunnyquiver** [comment]
I have gone back to the old and hopefully correct implementation of the function.  It might be slow for big examples.

**Comment by Nakayamaalgebra** [comment]
Thanks.
The old function is really slow. It might be faster to check whether the order of the Nakayama automorphism is equal to 1 (which is equivalent to the algebra being symmetric).

**Comment by Nakayamaalgebra** [comment]
Thank you for the answer. There might be no easy solution then. A good test whether a selfinjective algebra A is symmetric is to check whether the center of A (zeroth Hochschild cohomology) has the same vector space dimension as A/[A,A] (zeroth Hochschild homology). In fact, I do not know whether this is equivalent to a selfinjective algebra A being symmetric.
